stages:
  data_ingestion:
    cmd: python src/Facerecognition/pipeline/stage_01_data_ingetion.py
    deps:
      - src/Facerecognition/pipeline/stage_01_data_ingetion.py
      - src/Facerecognition/config/configuration.py
      - src/Facerecognition/components/data_ingetion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Facerecognition

  data_preprocessing:
    cmd: python src/Facerecognition/pipeline/stage_02_data_preprocess.py
    deps:
      - src/Facerecognition/pipeline/stage_02_data_preprocess.py
      - config/config.yaml
    outs:
      - artifacts/data_preprocessing/preprocessed_images


  prepare_base_model:
    cmd: python src/Facerecognition/pipeline/stage_03_prepare_model.py
    deps:
      - src/Facerecognition/pipeline/stage_03_prepare_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES

    outs:
      - artifacts/prepare_base_model



  training:
    cmd: python src/Facerecognition/pipeline/stage_04_training.py
    deps:
      - src/Facerecognition/pipeline/stage_04_training.py
      - src/Facerecognition/components/prepare_callbacks.py
      - config/config.yaml
      - artifacts/data_preprocessing/preprocessed_images
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHES
      - BATCH_SIZE
    outs:
      - artifacts/training/model.h5


  

  evaluation:
    cmd: python src/Facerecognition/pipeline/stage_05_evaluation.py
    deps:
      - src/Facerecognition/pipeline/stage_05_evaluation.py
      - config/config.yaml
      - artifacts/data_preprocessing/preprocessed_images
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false